name: Reorganize README

on:
  push:
    branches-ignore: [reorganize-ci]

jobs:
  reorganize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: run the script
        run: |
          cd scripts
          npm install
          npm run main -- https://github.com/${{ github.repository }}/ ../README.md ../README.md
      - uses: actions/upload-artifact@v2
        with:
          name: readme
          path: README.md
