name: Reorganize README

on:
  push:
    branches: [master]

jobs:
  reorganize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: run the script
        id: run_script
        run: |
          cd scripts
          npm install
          npm run main -- "https://github.com/${{ github.repository }}/blob/${GITHUB_REF##*/}/" ../README.md ../README.md > output
          echo "::set-output name=script::$(cat output)"
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Reorganize README.md
          branch: reorganize-ci
          add-paths: README.md
          delete-branch: false
          title: '[CI] Reorganize README.md'
          body: |
            This is a CI that makes sure entries are in alphabetical order and no links are invalid.

            Output from script:
            ```
            ${{ steps.run_script.outputs.script }}
