name: Reorganize README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  reorganize:
    if: github.ref != 'refs/heads/reorganize-ci'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: run the script
        run: |
          cd scripts
          npm install
          npm run main -- "https://github.com/${{ github.repository }}/blob/${GITHUB_REF##*/}/" ../README.md ../README.md
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: Reorganize README.md
          branch: reorganize-ci
          delete-branch: false
          title: '[CI] Reorganize README.md'
          body: |
            This is a CI that makes sure entries are in alphabetical order and no links are invalid.
